#ifndef DATA_H
#define DATA_H

#include <QDateTime>

typedef struct{
    double x;
    double y;
    double r;
    void setValue(double a,double b,double c){
        x=a;y=b;r=c;
    }
} Data;

/** @brief Structure motion struct */

   struct Motion
   {
       QDateTime timeStamp;            ///< A variable of QDataTime class provides date and time function
       int heartSignal;                ///< Heart signal.It is used to avoid losing message at the process of reporting data
       int translation;                ///< Distance changes between two moments.
       int rotation;                   ///< Angle changes between two moments.
       int orientation;                ///< Angle changed relatives to original point
       int xPosition;                  ///< X location in Cartesian coordinates
       int yPosition;                  ///< Y location in Cartesian coordinates

       int leftFront;                  ///< The orginal data is generated by left front encoder in a robot.
       int leftBack;                   ///< The orginal data is generated by left back encoder in a robot.
       int rightFront;                 ///< The orginal data is generated by right front encoder in a robot.
       int rightBack;                  ///< The orginal data is generated by right back encoder in a robot.
       int leftSide;                   ///< To judg the left side wheel in a robot is foreward.
       int rightSide;                  ///< To judg the right side  wheel in a robot is reverse.
   };

#endif // DATA_H
